<!DOCTYPE html><html lang="cs" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width , initial-scale=1.0 , viewport-fit=cover"><link rel="stylesheet" href="css/css.8.css"><meta name="description" content="Boar-cz ve svém portfoliu představuje webové projekty: prezentační weby, webové články a webové aplikace. Precizní webové stránky to je Boar-cz."><meta name="keywords" content="webové projekty,webové stránky,web"><meta name="author" content="Boar-cz"><meta name="application-name" content="Boar-cz"><meta property="og:url" content="https://www.boar-cz.info"><meta property="og:title" content="Boar-cz webové stavby"><meta property="og:description" content="Boar-cz ve svém portfoliu představuje webové projekty: prezentační weby, webové články a webové aplikace. Precizní webové stránky to je Boar-cz."><meta property="og:image" content="https://www.boar-cz.info/nahled/nahled.gif"><meta property="og:image:type" content="image/gif"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:update_time" content="2024-08-04T18:00:00+01:00"><meta property="og:locale" content="cs_CZ"><meta property="og:site_name" content="Boar-cz"><meta property="og:type" content="article"><meta property="article:published_time" content="2024-01-01T18:00:00+1:00"><meta property="article:modified_time" content="2024-08-04T18:00:00+1:00"><meta property="article:section" content="Jazyky na tvorbu webové stránky,Nástroje pro tvorbu webové stránky,Kontrola kvality webové stránky,Webové projekty"><meta property="article:tag" content="Boar-cz"><meta name="robots" content="index,follow"><meta property="twitter:card" content="summary_large_image"><meta property="twitter:site" content="@boar-cz"><meta property="twitter:url" content="https://www.boar-cz.info/"><meta property="twitter:title" content="Boar-cz webové stavby"><meta property="twitter:description" content="Boar-cz ve svém portfoliu představuje webové projekty: prezentační weby, webové články a webové aplikace. Precizní webové stránky to je Boar-cz."><meta property="twitter:image" content="https://www.boar-cz.info/nahled/nahled.gif"><link rel="apple-touch-icon" sizes="180x180" href="favicon/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="favicon/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="favicon/favicon-16x16.png"><link rel="manifest" href="favicon/site.webmanifest"><link rel="mask-icon" href="favicon/safari-pinned-tab.svg" color="#5bbad5"><meta name="msapplication-TileColor" content="#ffc40d"><meta name="theme-color" content="#ffffff"><title>Boar-cz webové stavby</title>
<script type="application/ld+json">
{
"@context": "https://schema.org/",
"@type": "Article",
"mainEntityOfPage": {
"@type": "WebPage",
"@id": "https://www.boar-cz.info"
},
"headline": "Precizní webové stránky to je Boar-cz",
"description": "Boar-cz na svém webu představuje své portfolio a také webové projekty respektive webové stránky, které vyrobil.",
"image": {
"@type": "ImageObject",
"url": "https://www.boar-cz.info/svg/logo.svg",
"width": "400",
"height": "400"
},
"author": {
"@type": "Person",
"name": "Mgr. Bc. Michal Raus",
"url": "https://www.boar-cz.info"
},
"publisher": {
"@type": "Organization",
"name": "Boar-cz",
"logo": {
"@type": "ImageObject",
"url": "https://www.boar-cz.info/svg/logo.svg",
"width": "400",
"height": "400"
}
},
"datePublished": "2024-01-01",
"dateModified": "2024-08-04"
}
</script>
</head><body class="fl jc"><div class="h-con"><header id="hd" class="fl jc ac co"><div class="l-p fl jc tc co"><p>Boar-cz</p><p class="m0">webové stavby</p></div><nav class="h-n"><ol class="menu"> <li class="fl jc ac"><a id="m1" href="#boar-cz" title="Boar-cz webové stavby">Boar-cz</a></li> <li class="fl jc ac"><a id="m2" href="#webove-projekty" title="Web projekty">Webové projekty</a></li> <li class="fl jc ac"><a href="kontakt/" title="Kontaktní formulář">Kontakt</a></li></ol></nav><div id="c-svg" class="l-box fl ac jc"><svg class="l-svg" width="400" height="400" viewBox="0 0 400 400" stroke-width="10" stroke-linejoin="round" stroke="rgb(110,87,168)" fill="none"><defs><filter id="fil1" filterUnits="userSpaceOnUse" x="0" y="0" width="400" height="400"><feGaussianBlur in="SourceAlpha" stdDeviation="4" result="blur"/><feOffset in="blur" dx="4" dy="4" result="offsetBlur"/><feSpecularLighting in="blur" surfaceScale="5" specularConstant="0.75" specularExponent="200" lighting-color="#bbbbbb" result="specOut">
<fePointLight x="-5000" y="-10000" z="20000"/></feSpecularLighting><feComposite in="specOut" in2="SourceAlpha" operator="in" result="specOut"/><feComposite in="SourceGraphic" in2="specOut" operator="arithmetic" k1="0" k2="1" k3="1" k4="0" result="litPaint"/><feMerge><feMergeNode in="offsetBlur"/><feMergeNode in="litPaint"/></feMerge></filter></defs><g id="logo"><g filter="url(#fil1)" ><g stroke="black" fill="black" stroke-width="1"><path d="M 94,91 C 55,84 46,65 37,27 27,76 23,101 57,143 Z" /><path d="m 303,91 c 39,-7 48,-26 57,-64 10,49 14,74 -20,116 z" /></g><circle cx="200" cy="200" r="150" /><path d="m 200,50 c -109,89 -128,186 0,297" /><path d="m 200,50 c 109,89 128,186 0,297" /><path d="M 200,50 V 348" /><path d="m 89,100 c 60,13 106,36 222,0" /><path d="M 89,298 C 148,286 195,262 311,297" /><path d="M 346,192 54,193" /><g stroke="black" fill="black" stroke-width="1"><circle cx="125" cy="195" r="25" /><circle cx="275" cy="195" r="25" /></g></g></g></svg></div></header><main>
<article id="boar-cz" class="pt1"><div class="bc1"> </div><div class="fl jc"><div class="bM"><h1 class="tc">Boar-cz <span class="ibb">webové stavby</span></h1><div class="fl jc"><div class="col2"><p><strong>Boar-cz</strong> produkuje webové stavby. Stavění webů zahrnuje <strong>programování</strong>: prezentačních webových stránek, webových článků a&nbsp;webových aplikací.</p><p><mark>Značku <span class="ib">Boar-cz</span> produkuje jeden programátor</mark>, přesto&nbsp;se <span class="ib">o&nbsp;Boar-cz</span> hovoří jako o&nbsp;nás. <em>Uznejte samy, že&nbsp;podepisování webových stránek vlastním jménem včetně titulů, není zrovna trendy.</em></p><p><dfn><span class="ib">Název Boar-cz</span></dfn> je&nbsp;složenina anglického slova divočák a&nbsp;cz označuje zemi původu Czech Republic.</p></div></div><div class="fl jc"><ul id="kar1" class="kar jc ac"> <li id="k1a">Jednoduché řešení</li> <li id="k1b">Kvalitní kód</li> <li id="k1c">Responzivita</li> <li id="k1d">Rychlý web</li> <li id="k1e">Dobré SEO</li>
<li id="k1f">Jedinečný vzhled</li> <li> </li></ul></div><div class="fl jc"><figure class="o o1"><div class="r"><picture><source media="(min-width:500px)" srcset="jpg/f-s-3.jpeg"> <img width="200" height="200" src="jpg/f-m-3.jpeg" alt="Programátor Boar-cz" loading="lazy"></picture></div><figcaption>&copy;&#8239;2024 Programátor Boar-cz kóduje webový projekt</figcaption></figure></div><div class="but butP"> <a href="programator/" title="Kdo je programátor Boar-cz"><div class="ico1"> </div><p class="m0">Informace o&nbsp;programátorovi <span class="ib">Boar-cz</span></p></a></div><div id="u1" class="fl re ac co"><p id="u1a">programování</p><p id="u1b">webových stránek</p><p id="u1c"> <span class="ibb"><svg class="l-svg2" width="40" height="40" viewBox="0 0 400 400" stroke-width="10" stroke-linejoin="round" stroke="rgb(110,87,168)" fill="none"><use xlink:href="#logo" /></svg></span>Boar-cz</p></div></div></div><section><div class="bc2"> </div><div class="fl jc"><div class="bM">
<h2 class="n2 tc">Stavba webové stránky</h2><div class="fl jc"><div class="col2"><p>Naše <strong>webové stránky jsou kódovány základními jazyky</strong> pro&nbsp;programování webových projektů. Na&nbsp;přání můžeme přidat framework Vue&#8239;3.</p><p>Při&nbsp;návrhu a&nbsp;realizaci validních, responzivních a&nbsp;rychlých webových stránek <strong>prosazujeme jednoduchost a&nbsp;přehlednost</strong>.</p><p><dfn>Jednoduchost</dfn> neznamená kódování primitivních webů, ale&nbsp;programování efektivních a&nbsp;rychlých webových stránek.</p><p><dfn>Přehlednost</dfn> pro&nbsp;nás znamená vkládání do&nbsp;projektů pouze přínosné objekty. Nevkládáme do&nbsp;projektu objekty, které&nbsp;jsou pro&nbsp;návštěvníka pouze líbivé, ale&nbsp;v&nbsp;důsledku návštěvníkovi odebírají pozornost právě od&nbsp;věcí podstatných.</p></div></div><div class="fl jc"><ul id="kar2" class="kar jc ac"> <li id="k2a">HTML&#8239;5</li> <li id="k2b">CSS&#8239;3</li> <li id="k2c">JavaScript&#8239;ES6</li> <li id="k2d">VUE&#8239;3</li>
<li id="k2e">SVG-XML</li> <li id="k2f">PHP&#8239;7</li> <li> </li></ul></div><div class="fl vol bg"><div class="bg-r col2"><p>Ve&nbsp;světě internetu je&nbsp;možné se&nbsp;setkat s&nbsp;weby, které&nbsp;jsou graficky líbivé, ovšem pomalé a&nbsp;nepřehledné.</p><p>Například šablonové webové stránky s&nbsp;množstvím kýčovitých fotografií z&nbsp;fotobank a&nbsp;rozsáhlého menu skrytého v&nbsp;hamburgeru.</p><p>Obdobné webové stránky, návštěvníka nepotěší čekáním na obsah webové stránky, nepřehlednosti a&nbsp;<dfn>chybovosti</dfn> (přetečení textu, příliš malý text) v&nbsp;procházení webu.</p></div></div><div class="fl jc"><figure class="o o2"><div class="r"><picture><source media="(min-width:500px)" srcset="jpg/f-s-1.jpeg"> <img width="200" height="200" src="jpg/f-m-1.jpeg" alt="Knihy na kódování webové stránky" loading="lazy"></picture></div><figcaption>&copy;&#8239;2024 Knihy ke&nbsp;kódování webové stránky</figcaption></figure></div></div></div></section><section><div class="bc3"> </div>
<div class="fl jc"><div class="bM"><h2 class="n2 tc">Nástroje na&nbsp;stavbu webové stránky</h2><div class="fl jc"><div class="col2"><p><strong><dfn>Jazyky webové stránky</dfn> (HTML, JavaScriptu a&nbsp;CSS) kódujeme ve&nbsp;<abbr>Visual Studio Code</abbr> (VSC).</strong></p><p>Obrázky SVG kreslíme  v&nbsp;Inkscape a&nbsp;výsledný kód upravujeme. Na&nbsp;optimalizaci a&nbsp;úpravu rastrových obrázků používáme Adobe PhotoShop.</p><p>Výsledný <strong>kód webové stránky se&nbsp;ladí v&nbsp;DevTools</strong>.</p><p>GIT&nbsp;nám dává plnou kontrolu nad&nbsp;vývojem projektů a&nbsp;GitHub zálohuje naše projekty.</p><p>Při&nbsp;práci se&nbsp;serverem používáme Filezilla.</p><p>Používáme i&nbsp;doplňkové balíčky Node.js (glyphhanger) a&nbsp;umělou inteligenci chatGPT.</p></div></div><div class="fl jc"><ul id="kar3" class="kar jc ac"> <li id="k3a">Visual Studio Code</li> <li id="k3b">Inkscape</li> <li id="k3c">Adobe PhotoShop</li> <li id="k3d">Filezilla</li> <li id="k3e">DevTools Edge/Chrome</li> <li id="k3f">GIT</li>
<li> </li></ul></div><div class="fl vol bg"><div class="bg-r col2"><p>Boar-cz tvoří kód webových stránek. <strong>Kód nepíšeme v&nbsp;jedničkách a&nbsp;nulách</strong>, ale&nbsp;skládáme písmeno za&nbsp;písmenem, tag za&nbsp;tagem.</p><p>Pokud kreslíme SVG, výsledný kód dostatečně očistíme. V&nbsp;případě rastrových obrázků dostatečně pro&nbsp;web optimalizujeme.</p><p>Když&nbsp;si nevíme rady obrátíme&nbsp;se na&nbsp;umělou inteligenci chatGPT, který nám s&nbsp;kódem zaručeně poradí.</p></div></div><div class="fl jc"><figure class="o o2"><div class="r"><picture><source media="(min-width:500px)" srcset="jpg/f-s-2.jpeg"> <img width="200" height="200" src="jpg/f-m-2.jpeg" alt="Bankovky České koruny" loading="lazy"></picture></div><figcaption>&copy;&#8239;2024 Silný nástroj pro&nbsp;návrh, vývoj a&nbsp;realizaci webového projektu</figcaption></figure></div></div></div></section><section><div class="bc4"> </div><div class="fl jc"><div class="bM"><h2 class="n2 tc">Kontrola kvality webové stránky</h2>
<div class="fl jc"><div class="col2"><p>Kvalita kódu je&nbsp;pro&nbsp;nás důležitá!<strong> Všechny webové stránky, které vyrábíme jsou validní</strong> a&nbsp;v&nbsp;souladu s&nbsp;<abbr>World Wide Web Consortium</abbr> (W3C).</p><p><mark>Na&nbsp;prvním místě je&nbsp;validita, za&nbsp;ní následuje rychlost načítání webu a&nbsp;nezapomínáme ani na&nbsp;SEO</mark>.</p><p><strong>Bezchybné zobrazování, fungování a&nbsp;responzivitu</strong> testujeme přímo na&nbsp;<dfn>zařízeních různého druhu</dfn> (telefony, tablety a&nbsp;počítače s&nbsp;operačním systémem iOS, Android a&nbsp;Windows).</p></div></div><ul class="fl ul-a"> <li> <a href="https://seo-servis.cz/source-zdrojovy-kod/" title="Test kvality zdrojového kodu" target="_blank" rel="nofollow"><div class="ba"> </div><div class="bp"><p>Otestovat kvalitu kódu</p><p>webové stránky</p></div></a></li> <li> <a href="https://www.seotestonline.cz" title="SEO test webu od Creation" target="_blank" rel="nofollow"><div class="ba"> </div><div class="bp">
<p>Otestovat SEO (Creation.cz)</p><p>webové stránky</p></div></a></li> <li> <a href="https://www.seotest.seolight.cz" title="SEO test webu od Seolight" target="_blank" rel="nofollow"><div class="ba"> </div><div class="bp"><p>Otestovat SEO (Seolight.cz)</p><p>webové stránky</p></div></a></li> <li> <a href="https://pagespeed.web.dev" title="Test výkonu na PageSpeed" target="_blank" rel="nofollow"><div class="ba"> </div><div class="bp"><p>Otestovat výkon</p><p>webové stránky</p></div></a></li> <li> <a href="https://firefox-source-docs.mozilla.org/devtools-user/validators/" title="Test validyty HTML, CSS, SVG" target="_blank" rel="nofollow"><div class="ba"> </div><div class="bp"><p>Otestovat validitu</p><p>webové stránky</p></div></a></li> <li> <a href="https://validator.schema.org" title="Validátor schema.org" target="_blank" rel="nofollow"><div class="ba"> </div><div class="bp"><p>Otestovat JSON-LD</p><p>webové stránky</p></div></a></li></ul><div class="fl jc"><div class="col2">
<p><mark>Existuje více možností, jak&nbsp;vytvořit webovou stránku bez&nbsp;nutnosti programování</mark>.</p><p>Můžeme koupit šablonu webu, použít generátor webové stránky, web je&nbsp;možné vytvořit například i&nbsp;v&nbsp;Microsoft Wordu.</p><p>Kdo&nbsp;měl možnost vytvořit webovou stránku v&nbsp;něčem podobném, nám&nbsp;jistě dá&nbsp;za&nbsp;pravdu, že&nbsp;<strong>kvalita kódu těchto projektů je&nbsp;nevalná</strong>, rychlost načítání tristní, SEO mizerné, responzivita pokulhává a&nbsp;velikost webové stránky je&nbsp;gigantická.</p></div></div></section><section id="webove-projekty" class="s2"><div class="bc5"> </div><div class="but-m p05"> <a id="pb" href="#hd" title="Posun na Menu"><svg class="" width="50" height="32.5" viewBox="0 0 200 150" stroke="black" stroke-width="20" stroke-linecap="round" stroke-linejoin="round" fill="none"><path d="M 50,35 100,13 150,35">
<animate id="m_5" begin="m_4.end + 250ms" attributeName="stroke" from="black" to="rgb(168,87,104)" dur="100ms" fill="freeze" calcMode="paced" /><animate id="m_6" begin="m_5.end" attributeName="stroke" from="rgb(168,87,104)" to="black" dur="100ms" fill="freeze" calcMode="paced" /></path><path d="m 25,85 75,-30 75,30"><animate id="m_3" begin="m_2.end + 250ms" attributeName="stroke" from="black" to="rgb(168,87,104)" dur="100ms" fill="freeze" calcMode="paced" /><animate id="m_4" begin="m_3.end" attributeName="stroke" from="rgb(168,87,104)" to="black" dur="100ms" fill="freeze" calcMode="paced" /></path><path d="m 15,135 85,-33 85,33"><animate id="m_1" begin="0s ; m_6.end + 1s" attributeName="stroke" from="black" to="rgb(168,87,104)" dur="100ms" fill="freeze" calcMode="paced" /><animate id="m_2" begin="m_1.end" attributeName="stroke" from="rgb(168,87,104)" to="black" dur="100ms" fill="freeze" calcMode="paced" /></path></svg> Posun na&nbsp;Menu</a></div><div class="fl jc"><div class="bM">
<h2 class="hx">Webové projekty</h2><div class="pr"><div><p id="por">Boar-cz</p><ul class="ul2"> <li id="por1">Prezentační weby</li> <li id="por2">Webové články</li> <li id="por3">Webové aplikace</li></ul></div><div class="fl jc ac bg"><svg class="l-svg2" width="40" height="40" viewBox="0 0 400 400" stroke-width="10" stroke-linejoin="round" stroke="rgb(110,87,168)" fill="none"><use xlink:href="#logo" /></svg></div></div><div class="col"><p><mark><strong>Prezentační weby</strong></mark> mohou zahrnovat od&nbsp;tvorby životopisu, osobního webu, prezentace živnosti až&nbsp;po&nbsp;prezentaci portfolia firmy. Pokud o&nbsp;sobě, své&nbsp;živnosti anebo firmě chcete dát ve&nbsp;světě internetu patřičně vědět, je&nbsp;prezentační webová stránka správnou volbou. V&nbsp;době digitálních technologií je&nbsp;prezentační web <mark>nejlepší možnost, jak&nbsp;oslovit velké množství lidí</mark>, budoucích zákazníku anebo&nbsp;obchodních partnerů.</p>
<p><mark><strong>Webové články</strong></mark> patří spíše do&nbsp;blogů než na&nbsp;samostatnou webovou stránku. Nemusí tomu tak být! Pokud bude vašim záměrem <mark>oslovit čtenáře něčím lepším než pouhým textem</mark>, je&nbsp;webový článek zajímavým řešením a&nbsp;rozhodně změnou pro&nbsp;čtenáře. Nevěříte? Přesvědčit se&nbsp;můžete v&nbsp;projektu <a id="p1" href="#pk" title="Projekt Pěstování konopí a trest">Pěstování konopí a&nbsp;trest</a>, kde je&nbsp;homepage webovým článkem.</p>
<p><mark><strong>Webové aplikace</strong></mark> přináší možnosti, jak&nbsp;uživatele upoutat a&nbsp;rychlím způsobem mu umožnit <mark>výpočet prakticky čehokoli</mark>. Jednoduchou a&nbsp;však jedinečnou webovou aplikací je <a href="https://www.pestovani-konopi.info/kalkulator/" title="Přejít na Kalkulátor trest za pěstování konopí" target="_blank" rel="follow">Kalkulátor trestu za&nbsp;pěstování konopí</a>. Webové aplikace mají ovšem svá omezení, jak&nbsp;je možné se&nbsp;přesvědčit v&nbsp;projektu <a id="p2" href="#nv" title="Projekt Noční VLK">Noční VLK</a>.</p></div></div></div><section id="nv"><div class="fl jc cc"><p>projekt</p><div class="fl jc ac"><p>1</p></div></div><h3 class="n3 tc">Noční VLK</h3><div class="jc ac g-p"><div><p class="m0"><strong>Description</strong></p><p class="ha m4">On-line webová aplikace, která pohlídá časové intervaly pro&nbsp;kontrolní obchůzky: objektu, věcí anebo osob.</p><p class="m0"><strong>Podrobněji</strong></p>
<p class="ha m4"><mark>Noční VLK je&nbsp;webovou aplikací</mark>, která balancuje na&nbsp;samé hraně možností webové aplikace. Jedná&nbsp;se o&nbsp;webovou aplikaci, která vyžaduje autonomii v&nbsp;zařízení, ve&nbsp;kterém je&nbsp;spuštěna. Aplikace uživatele vyzývá ke&nbsp;konkrétním obchůzkám podle zvolených okruhů a&nbsp;délky intervalu, tyto obchůzky po&nbsp;potvrzení zapisuje a&nbsp;ukládá.</p></div><div class="l1"> </div><div><p class="m0"><strong>Požadavky</strong></p><p class="ha m4">Aplikace vyžaduje JavaScript. Velikost displeje na&nbsp;šířku alespoň 280&#8239;px a&nbsp;na&nbsp;výšku alespoň 400&#8239;px. <strong>Aplikace musí být v&nbsp;zařízení viditelně na&nbsp;obrazovce</strong>. Nesmí být překryta jinou aplikací anebo minimalizována. Během používání aplikace, nesmí být zařízení uzamčeno anebo v&nbsp;režimu spánku.</p><p>&copy;&#8239;2023 Boar-cz</p></div></div>
<div class="but"><a href="nocni-vlk/" title="Přejít na aplikaci Noční VLK" target="_blank">Ukázat projekt <span class="ib">Noční&nbsp;VLK</span></a></div></section><section id="pk"><div class="fl jc cc"><p>projekt</p><div class="fl jc ac"><p>2</p></div></div><h3 class="n3 tc">Pěstování konopí a&nbsp;trest</h3><div class="jc ac g-p"><div><p class="m0"><strong>Description</strong></p><p class="ha m4">Poznejte trest za&nbsp;pěstování konopí s&nbsp;obsahem psychotropní látky THC&#8239;›&#8239;1%. Přehledně množství gramů rostliny konopí a&nbsp;možný trest odnětí svobody.</p><p class="m0"><strong>Podrobněji</strong></p>
<p class="ha m4">Webový projekt Pěstování konopí a&nbsp;trest je&nbsp;možné zařadit do&nbsp;<mark>kategorie webových článků</mark>. Návštěvníkům se&nbsp;snaží pomocí animací a&nbsp;zjednodušení přiblížit trestněprávní rovinu pěstování konopí ve&nbsp;všech jeho fázích: pěstování, sklizeň a&nbsp;skladování. <mark>Součástí</mark> tohoto webového článku je&nbsp;také <mark>webová aplikace</mark> Kalkulátor trestu za&nbsp;pěstování konopí.</p></div><div class="l2"> </div><div><p class="m0"><strong>Požadavky</strong></p><p class="ha m4">Velikost displeje na&nbsp;šířku alespoň 280&#8239;px a&nbsp;na&nbsp;výšku alespoň 300&#8239;px. Webová stránka <strong>bezprostředně nevyžaduje JavaScript</strong>, ale&nbsp;s&nbsp;jeho pomocí, se&nbsp;zvýší uživatelský zážitek o&nbsp;animace. Aplikace Kalkulátor trestu a&nbsp;kontaktní formulář, které jsou součástí webové stránky vyžadují JavaScript.</p><p>&copy;&#8239;2023 Boar-cz</p></div></div>
<div class="but"><a href="https://www.pestovani-konopi.info" title="Přejít na Pěstování konopí a trest" target="_blank" rel="follow">Ukázat projekt Pěstování&nbsp;konopí a&nbsp;trest</a></div></section><section id="wp"><div class="fl jc cc"><p>projekt</p><div class="fl jc ac"><p>3</p></div></div><h3 class="n3 tc">Boar-cz <span class="ibb fm">webové stránky</span> <span class="ibb fm">na&nbsp;přání</span></h3><div class="jc ac g-p"><div><p class="m0"><strong>Description</strong></p><p class="ha m4">Boar-cz ve svém portfoliu představuje webové projekty: prezentační weby, webové články a webové aplikace. Precizní webové stránky to je Boar-cz.</p><p class="m0"><strong>Podrobněji</strong></p>
<p class="ha m4">Webový projekt Boar-cz je&nbsp;<mark>prezentační web</mark>. Ve&nbsp;svém souhrnu prezentuje Boar-cz jakožto výrobce webových stránek. U&nbsp;tohoto projektu je&nbsp;<strong>důraz kladen především na&nbsp;<abbr>výkon</abbr></strong> (rychlost načítání webové stránky) a&nbsp;na&nbsp;přehlednost poskytnutých informací. Součástí webové stránky je&nbsp;<mark>kontaktní formulář</mark>, který <strong>je&nbsp;<abbr>univerzální</abbr></strong> (po&nbsp;změně loga, fontu a&nbsp;barev, je&nbsp;možné ho&nbsp;použít na&nbsp;jakýkoli web) a&nbsp;právem si&nbsp;zaslouží zařadit do&nbsp;<mark>kategorie webové aplikace</mark>. </p></div><div class="l3"><svg class="l-svg" width="40" height="40" viewBox="0 0 400 400" stroke-width="10" stroke-linejoin="round" stroke="rgb(110,87,168)" fill="none"><use xlink:href="#logo" /></svg></div><div><p class="m0"><strong>Požadavky</strong></p>
<p class="ha m4">Velikost displeje na šířku alespoň 280&#8239;px a na výšku alespoň 300&#8239;px. Webová stránka <strong>bezprostředně nevyžaduje JavaScript</strong>, ale s jeho pomocí, se zvýší uživatelský zážitek o animace. Kontaktní formulář, který je součástí webové stránky, vyžaduje JavaScript.</p><p>&copy;&#8239;2024 Boar-cz</p></div></div><div class="m1 s2"><p class="tc f2">Na&nbsp;tomto projektu se&nbsp;právě nacházíte.</p></div></section><section id="sv"><div class="fl jc cc"><p>projekt</p><div class="fl jc ac"><p>4</p></div></div><h3 class="n3 tc">Šifrovač</h3><div class="jc ac g-p"><div><p class="m0"><strong>Description</strong></p><p class="ha m4">On-line šifrování textu. Bezpečnější zasílání textových zpráv pomocí šifrování.</p><p class="m0"><strong>Podrobněji</strong></p>
<p class="ha m4">Šifrovač je&nbsp;<mark>webová aplikace</mark>, díky které můžete textové zprávy předávat bezpečněji. Uživatelé si&nbsp;mohou pomocí této aplikace a&nbsp;Unikátního kódu&nbsp;(UC) předávat textové zprávy v&nbsp;šifrované podobě. Šifrovaný text je&nbsp;možné posílat například emailem, messengerem nebo&nbsp;smskou. <mark>Aplikace je&nbsp;naprogramovaná ve&nbsp;frameworku Vue&#8239;3.</mark></p></div><div class="l4"> </div><div><p class="m0"><strong>Požadavky</strong></p><p class="ha m4">Velikost displeje na&nbsp;šířku alespoň 280&#8239;px a&nbsp;na&nbsp;výšku také alespoň 280&#8239;px. Webová stránka <strong>bezprostředně vyžaduje JavaScript</strong>. Prostředí aplikace bylo navrženo tak, aby její používání bylo jednoduché a&nbsp;přitom efektivní.</p><p>&copy;&#8239;2024 Boar-cz</p></div></div><div class="but"><a href="sifrovac/" title="Přejít na Šifrovač" target="_blank" rel="follow">Ukázat projekt Šifrovač</a></div></section></section></article></main><aside class="fl bokem co">
<div class="fl b-s"><div class="b-s2"> <a class="fl a-s ac" href="o-webu/" title="Informace o webu"><div class="ico1"> </div> Informace o&nbsp;webové stránce</a></div><div class="b-s2"> <a id="sdil-fb" class="fl a-s ac" href="https://www.facebook.com/sharer/sharer.php?u=https://www.boar-cz.info" title="Sdílet Boar-cz na FB" target="_blank" rel="nofollow"><div class="ico2"> </div> Sdílet na&nbsp;Facebooku</a></div><div class="b-s2"> <a id="sdil-tw" class="fl a-s ac" href="https://twitter.com/intent/tweet?url=https://www.boar-cz.info&text=" title="Sdílet Boar-cz na X" target="_blank" rel="nofollow"><div class="ico3"> </div> Sdílet na&nbsp;Twitteru</a></div></div><div class="fl b-s"><div><p>Partnerské stránky</p><ul> <li><a href="https://www.pestovani-konopi.info" title="Trest za pěstování konopí" target="_blank" rel="follow">Pěstování konopí a trest</a></li> <li><a href="https://www.pestovani-konopi.cz" title="Doména k prodeji" target="_blank" rel="follow">Pěstování konopí.cz - doména k prodeji </a></li></ul>
</div><div><p>Kvalita webu</p><ul> <li><a href="https://seo-servis.cz/source-zdrojovy-kod/16102353" title="Kvalita zdrojového kódu" target="_blank" rel="follow">Test kvality zdrojového kódu</a></li> <li><a href="https://pagespeed.web.dev/analysis/https-www-boar-cz-info/4z7wytcibn?form_factor=mobile" title="Rychlost načítání webu" target="_blank" rel="nofollow">Výkon webové stránky</a></li> <li><a href="https://www.seotestonline.cz/vysledek/63629-boar-cz-info.html" title="Seo test webu" target="_blank" rel="follow">Seo test webové stránky</a></li> <li><a href="https://www.webwiki.com/boar-cz.info" title="Hodnocení webu" target="_blank" rel="follow">Hodnocení webové stránky</a></li></ul></div></div></aside><footer class="pata tc"><p>&copy;&#8239;2024 Boar-cz</p><p class="fm">(všechna práva vyhrazena)</p><address><p>Máte otázku k&nbsp;těmto webovým&nbsp;stránkám? <a href="kontakt/" title="Kontakt na provozovatele webu">Kontaktujte&nbsp;nás</a></p></address></footer></div><script src="script/script.6.js" async> </script></body></html>